### ISSUE TITLE
display Resolution（4k）

### ISSUE THREAD

**Issue by wuvu** [672368201/x1c7-hackintosh#2]
Hello, my model is also 20r1, but my screen size is 4k (3840x2160), after using your EFI file, the screen display is not normal, please ask what file needs to be changed?

**Comment by 672368201** [comment]
Sorry, I'm not the original author of this project, and I'm not sure about how OpenCore works exactly, so this repley may not help you a lot.

You can load the config file EFI/OC/config.plist with OpenCore Configurator and navigate to DeviceProperties -> your graphic card path (path varies by device, in this case PciRoot(0x0)/Pci(0x2,0x0)), the key-value pairs under this section define how OpenCore interacts with your graphic card, combine OpenCore GPU Patching guide (https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/) with other existing X1C repositories referred in my project's README to creat your own config.plist, good luck!

<img width="1392" alt="截屏2023-02-21 17 47 18" src="https://user-images.githubusercontent.com/71371424/220319873-32dffe9f-5347-4b96-b174-8368ad03f62a.png">

**Comment by huangyijuab** [comment]
Thanks for the reply! I'll try it out and if I make any progress I'll post it here.
